### ISSUE TITLE
acgnx_Global无法勾选

### ISSUE THREAD

**Issue by demo0102** [AmusementClub/OKPGUI#1]
![image](https://user-images.githubusercontent.com/42965600/226533641-0c589993-753b-4a80-8608-e79f39ddc7a3.png)
按照readme文档进行操作，保存身份后无法勾选acgnx_Global，刚开始重启gui即可勾选，后来不知道什么操作无论如何也无法勾选acgnx_Global了。

**Comment by tastysugar** [comment]
请尝试 https://github.com/AmusementClub/OKPGUI/releases/tag/v0.1.4 看看是否有解决此问题，如果有，可以关闭这个 issue。
如果问题依旧存在，请再评论。

**Comment by demo0102** [comment]
问题已解决
